version: '3.8'

services:
  # spin up a database
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: turing
      POSTGRES_PASSWORD: turing
      POSTGRES_DB: fridger_app
    ports:
      - "5432"
    volumes:
      - fridger_app:/var/lib/postgresql/data

  # start up an API server
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    # some secrets that we want to pass:
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgres://turing:turing@postgres:5432/fridger_app
      TEST_DATABASE_URL: postgres://turing:turing@localhost:5432/testdb
      PORT: 3000
    ports:
      - "3000"
    depends_on:
      - postgres

  # start up a client (and proxy) server
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  fridger_app:
